# Generated by Django 5.2.15 on 2026-06-26 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("village", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("mobile", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Owner",
                "verbose_name_plural": "Owners",
                "db_table": "owners",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("plot_number", models.CharField(db_index=True, max_length=50)),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Area in Square Meter",
                        max_digits=12,
                    ),
                ),
                (
                    "land_use",
                    models.CharField(
                        choices=[
                            ("Agriculture", "Agriculture"),
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                            ("Industrial", "Industrial"),
                            ("Government", "Government"),
                            ("Others", "Others"),
                        ],
                        default="Agriculture",
                        max_length=30,
                    ),
                ),
                (
                    "polygon",
                    models.JSONField(help_text="Polygon Coordinates in GeoJSON format"),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="plot.owner",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="village.village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plot",
                "verbose_name_plural": "Plots",
                "db_table": "plots",
                "ordering": ["plot_number"],
                "indexes": [
                    models.Index(
                        fields=["plot_number"], name="plots_plot_nu_ac89cc_idx"
                    ),
                    models.Index(fields=["land_use"], name="plots_land_us_05593a_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("village", "plot_number"),
                        name="unique_plot_per_village",
                    )
                ],
            },
        ),
    ]
